# Generated by Django 3.1 on 2020-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество'),
        ),
    ]
